# Controls when the workflow will run
name : Github Action Example

#Controls when the worflow will run
on:
  #Triggers only for the main branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    #the type of runner that the job will run on (donc on peut utiliser commande move, delete...)
    runs-on: ubuntu-latest
    #Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
    #On va créer un dossier archive et copier tous les dossiers du repository dessus
    # Clean up the archive folder if it already exists
      - name: Clean up archive folder
        run: |
          if [ -d "archive" ]; then
            rm -rf archive
          fi

      # Create archive and copy files
      - name: Create archive and copy files
        run: |
          mkdir -p archive
          cp -r * archive/
    

